### ISSUE TITLE
Error getting channels

### ISSUE THREAD

**Issue by fqx** [yujincheng08/rust-iptv-proxy#10]
`Error getting channels: HTTP status client error (400 Bad Request) for url (http://183.59.153.24:8082/EPG/oauth/v2/token?`

广州电信，输入了正确的user, passwd, mac。
user是@iptv.gd前面的部分。
passwd是iptv的pppoe密码。
mac是华为电视盒子的mac地址。

但我用的是路由器（routeros)拨的pppeo，也尝试换过用路由器的mac，一样提示400错误。
请问从哪里查起？

**Comment by yujincheng08** [comment]
流量要走 iptv 那个 pppoe 接口

**Comment by fqx** [comment]
> 流量要走 iptv 那个 pppoe 接口

也写了对应路由
125.88.0.0/16
183.59.0.0/16

**Comment by fqx** [comment]
> 用 python 脚本试试？

你说的python脚本是哪个？

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/tellyget-gd

**Comment by fqx** [comment]
> https://github.com/yujincheng08/tellyget-gd

👍周末有时间试一下

**Comment by fqx** [comment]
@yujincheng08 这个python脚本也是用user, password, MAC来验证的，不是原版那个需要抓包的？其实也就是这个rust的python版？

`Found 0 channels
Filtered 0 channels
Removed 0 SD candidate channels`

**Comment by yujincheng08** [comment]
其实都是用 User password 和 mac 验证的。只不过相关接口不一样，理论上验证过程时一样的。

**Comment by fqx** [comment]
@yujincheng08 我抓了包，发现UserID和pppoe拨号的不一样。改成抓包的UserID就可以获得列表了。但是这个播放列表放到VLC里面还不能播放，我再看看是什么问题。

**Comment by yujincheng08** [comment]
难道是最近的用户验证账号和PPPoE账号吗。。不过验证账号可以在机顶盒设置里面查到的。

**Comment by yujincheng08** [comment]
不能播放可能是因为路由问题，播放地址的 ip 你不一定加到了路由表里面。

**Comment by yujincheng08** [comment]
> 125.88.0.0/16
183.59.0.0/16

这个路由表会导致某些 CDN 不能用。比如 QQ 图片😂

**Comment by fqx** [comment]
> > 125.88.0.0/16
> > 183.59.0.0/16
> 
> 这个路由表会导致某些 CDN 不能用。比如 QQ 图片😂

后面我可以写条件路由，现在问题是为啥不能放呢。

**Comment by yujincheng08** [comment]
或许可以打开 rstp-proxy 试试

**Comment by fqx** [comment]
rstp-proxy的作用是？

**Comment by yujincheng08** [comment]
rtsp 流量经过我们的程序转发，在指定网络接口之后可以不需要静态路由。

**Comment by fqx** [comment]
仍到xteve+plex里面可以播放了。
如果用rstp-proxy的话，哪个参数是设置代理服务器地址的？-a 还是 -I

**Comment by yujincheng08** [comment]
不需要设置地址呀，m3u8 的 rtsp 地址会自动改掉。

**Comment by fqx** [comment]
> 不需要设置地址呀，m3u8 的 rtsp 地址会自动改掉。

改出来的是哪个ip哪个端口呢，rust在这里成为了代理服务器，它自身的地址怎么设置。

**Comment by yujincheng08** [comment]
都是用同一个端口，用不同的 path 区分就行了

**Comment by yujincheng08** [comment]
这个 issue 的问题应该解决了。
