### ISSUE TITLE
无法指定udpxy或msd端口

### ISSUE THREAD

**Issue by YipSzeho** [yujincheng08/rust-iptv-proxy#14]
带udp-proxy参数导出的playlist的端口为7878，无法修改成udpxy或msd所转发的单播端口。博客中的--udp-proxy="192.168.1.1:4022"参数无法启动程序。

**Comment by yujincheng08** [comment]
我是自己实现了一个 udp-proxy

**Comment by YipSzeho** [comment]
大佬可以考虑加入支持自定义端口功能吗，我现在的环境下是只有--rtsp-proxy能用，但是部分设备播放会卡，--udp-proxy不能用。不过用msd转udp单播后可以流畅播放。
我是希望在所有内网设备(包括原来的机顶盒)都可以看IPTV。IPTV的pppoe由光猫完成，光猫开启IGMP Proxy或Snooping，树莓派op当旁路由使用vlan来访问IPTV专网。这样就能让原来的机顶盒也能用了。

**Comment by YipSzeho** [comment]
测试时分别单独开启本程序udp和msd
udp是一直无法播放的
![image](https://github.com/yujincheng08/rust-iptv-proxy/assets/58989046/89954a40-ceac-439e-9564-3f6ef92be4c8)
使用msd是可以的
![image](https://github.com/yujincheng08/rust-iptv-proxy/assets/58989046/81af2c72-fcd0-4e38-b2b8-5a0e3f5b1b0d)

**Comment by yujincheng08** [comment]
浏览器打开 `http://192.168.50.10:7878/udp/239.77.0.84:5146` 如何

**Comment by YipSzeho** [comment]
也是一直加载不出来喔
![image](https://github.com/yujincheng08/rust-iptv-proxy/assets/58989046/5ed00cdc-56d0-4e8a-b35c-6c463b27bca4)

**Comment by yujincheng08** [comment]
用 udpxy 在同样机器上能否正常工作？如果可以的话需要抓包看看是什么情况（可以只抓 udp 部分的）。

**Comment by yujincheng08** [comment]
也可能我的 udp-proxy 没绑定到接口上导致的，可以试试先加个路由，把多播地址路由到 iptv 的接口。

**Comment by yujincheng08** [comment]
尝试修复了一下，可以试试 https://github.com/yujincheng08/rust-iptv-proxy/commit/6c2f411d00fc62bea908cca95b75eb143b20bbb8

**Comment by YipSzeho** [comment]
好欸！完美解决了，谢谢大佬！
