### ISSUE TITLE
windows下如何绑定网口呢？

### ISSUE THREAD

**Issue by YipSzeho** [yujincheng08/rust-iptv-proxy#15]
openwrt可以用-I ethx来绑定网口，windows如何绑定呢？0v0

**Comment by yujincheng08** [comment]
也是 -I

**Comment by YipSzeho** [comment]
请问一下如何才能获取到windows的接口名呢，网上找了不少貌似都不正确

**Comment by YipSzeho** [comment]
下载了大佬最新编译的版本再试了试。单网卡下不带-I参数可以获取频道，但是带了-I指定网卡后无论单网卡还是多卡都不能获取。这样的启动命令有问题吗？
![无标题](https://github.com/user-attachments/assets/4c528d34-142f-4b62-8d8b-a065ac540a99)

**Comment by yujincheng08** [comment]
你开了代理？程序用了个 127.0.0.1:7897 的代理

**Comment by YipSzeho** [comment]
关闭代理后，带上-I参数依旧不行。不带-I参数时开不开代理都可以正常使用0v0

**Comment by yujincheng08** [comment]
看看这时候的日志？

**Comment by YipSzeho** [comment]
- 代理带-I
![代理带-I](https://github.com/user-attachments/assets/e9515ee3-41a2-41d8-aeec-16f404936cab)

- 代理不带-I
![代理不带-I](https://github.com/user-attachments/assets/1bc74955-af5a-4f47-b9a9-3a78497a0d9b)

- 无代理带-I
![无代理带-I](https://github.com/user-attachments/assets/89015221-60d0-4468-b222-bf85fb093f05)

- 无代理不带-I
![无代理不带-I](https://github.com/user-attachments/assets/44530aa4-b1d0-4cfe-b207-5cb0544b4732)

**Comment by yujincheng08** [comment]
目前我在 windows 上的实现是扫描接口，然后拿接口的第一个 ip 地址，然后调用 `reqwest` 的 [local_address](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.local_address)。在我的 windows 机子上测试能正确使用该接口。我怀疑是你的网络设置有点问题，可以抓包看看。

**Comment by yujincheng08** [comment]
比如一个可能的原因：该接口有两个 ip 地址。其中一个能连接网关；另一个却不能（比如跟网关不在同一个子网）。windows 路由表自动学习使用能连接网关的 ip 地址，而我的程序拿到的第一个 ip 地址是刚好是不能连到网关的，进而导致连接失败。
