### ISSUE TITLE
无法播放多个频道

### ISSUE THREAD

**Issue by YipSzeho** [yujincheng08/rust-iptv-proxy#16]
从 https://github.com/yujincheng08/rust-iptv-proxy/commit/504961ea571e515d6dcc805ca73318be97e83541 开始，所有设备只能播放同一个频道，任一设备切换频道所有设备都将同步。新设备无论从任何频道加入，所播放的都是其它设备正播放的频道。但是log的join和left信息似乎是正常的。
![image](https://github.com/user-attachments/assets/cc045210-1268-4edd-adec-3da98fa2f47d)

**Comment by yujincheng08** [comment]
看起来是忘记 reuseport 导致的

**Comment by yujincheng08** [comment]
试试 https://github.com/yujincheng08/rust-iptv-proxy/commit/d03882f0c1bdb523a07317d548a1978590b3f653

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/rust-iptv-proxy/commit/b10e80074c6f0c8fa4b1ba230fff7b968f1f6f18 应该好了

**Comment by YipSzeho** [comment]
好了好了
