### ISSUE TITLE
申请项目更新时同步发布预编译二进制文件

### ISSUE THREAD

**Issue by pk000** [yujincheng08/rust-iptv-proxy#5]
请问是否可以提供预编译二进制文件？或者通过Actions自动编译发布到release？
平时搭建编译环境不方便，希望可以增加预编译文件。

**Comment by yujincheng08** [comment]
可以，但是只提供 x86 的，不知是否足够

**Comment by pk000** [comment]
现在软路由都是x86_64居多，可以适配就好。
建议提供不依赖openwrt SDK的支持TLS版本。

**Comment by mrifoxer** [comment]
不知道能不能支持DHCP鉴权的IPTV环境啊

**Comment by yujincheng08** [comment]
DHCP 鉴权是创建 interface 时候的；你能获取到 IP 就行。获取播放地址的鉴权才是这个工具做的事。

**Comment by mrifoxer** [comment]
好的，明白了，期待编译好的文件

**Comment by pk000** [comment]
测试过[Initial release](https://github.com/yujincheng08/rust-iptv-proxy/releases/tag/0.0.1)，发现不用代理模式和使用rtsp代理模式都正常，但是udp代理模式无法获取视频。

日志如下：
`iptv-proxy: [INFO  actix_server::builder] starting 4 workers
iptv-proxy: [INFO  actix_server::server] Actix runtime found; starting in Actix runtime
iptv-proxy: [INFO  iptv::iptv] Obtaining channels
iptv-proxy: [INFO  iptv::iptv] Got 189 channel(s)
iptv-proxy: [INFO  retina::codec] no depacketizer for media/encoding_name video/mp2t
iptv-proxy: [INFO  iptv::proxy] RTSP session created with 1 streams
iptv-proxy: [INFO  retina::codec] no depacketizer for media/encoding_name video/mp2t
iptv-proxy: [INFO  iptv::proxy] RTSP session created with 1 streams
iptv-proxy: [INFO  iptv::proxy] Udp proxy joined 239.77.0.86:5146
iptv-proxy: [INFO  iptv::proxy] Udp proxy joined 239.77.0.84:5146
iptv-proxy: [INFO  iptv::proxy] Udp proxy joined 239.77.0.1:5146
iptv-proxy: [INFO  iptv::proxy] Udp proxy joined 239.77.0.138:5146
iptv-proxy: [INFO  iptv::proxy] Udp proxy joined 239.77.0.134:5146
iptv-proxy: [INFO  iptv::proxy] Udp proxy joined 239.77.0.217:5146
iptv-proxy: [INFO  iptv::proxy] Udp proxy joined 239.77.0.173:5146`

另外使用rtsp代理的时候，每次换台都有以下日志，不知道是否有问题：
`iptv-proxy: [INFO  retina::codec] no depacketizer for media/encoding_name video/mp2t`

**Comment by pk000** [comment]
udpxy是正常可以转发组播的。

OpenWRT上抓包不太会。

**Comment by yujincheng08** [comment]
可以参考 https://openwrt.org/docs/guide-user/firewall/misc/tcpdump_wireshark

**Comment by YipSzeho** [comment]
大佬可以编译一份aarch64的吗，尝试了好久都没办法编译成功（x86_64倒是可以编译的

**Comment by yujincheng08** [comment]
@YipSzeho 
[iptv.zip](https://github.com/user-attachments/files/16121922/iptv.zip)

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/rust-iptv-proxy/actions/runs/9839898342

有了，现在 CI 会自动编译了；目前有 x86_64, aarch64 和 mispel 三个架构。

**Comment by yujincheng08** [comment]
@pk000 udp-proxy 问题似乎解决了，试试最新 CI

**Comment by pk000** [comment]
udp-proxy 问题解决了。👍
